services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db/videodb
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=videodb

  redis:
    image: redis:6.2-alpine

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A backend.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db/videodb
      - PYTHONPATH=/app
    depends_on:
      - redis

volumes:
  postgres_data:
